services:
  postgres:
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - 4321:5432
    user: postgres
    environment:
      POSTGRES_DB: exercise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Beebadoo1!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - exdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - exdb

volumes:
  pgdata:

networks:
  exdb:
