services:
  postgres:
    image: postgres:16.4-alpine3.20
    restart: always
    ports:
      - 4321:5432
    user: postgres
    environment:
      POSTGRES_DB: exercise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Beebadoo1!
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - exdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./backend
    restart: always
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: exercise
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Beebadoo1!
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/openapi.json')" ]
      interval: 3s
      timeout: 5s
      retries: 20
    networks:
      - exdb

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - 5173:5173
    environment:
      VITE_API_BASE_URL: http://localhost:8000
    depends_on:
      api:
        condition: service_healthy
    networks:
      - exdb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - exdb

volumes:
  pgdata:

networks:
  exdb:
